In [6]:
import numpy as np

np_city = np.array([
  [1.64, 71.38],
  [1.37, 63.35],
  [1.68, 55.09],
  [2.04, 74.85],
  [2.04, 68.72],
  [2.01 ,73.57]
])
np_city



array([[ 1.64, 71.38],
       [ 1.37, 63.35],
       [ 1.68, 55.09],
       [ 2.04, 74.85],
       [ 2.04, 68.72],
       [ 2.01, 73.57]])

In [7]:
np.mean(np_city[:, 0])

1.7966666666666666

In [8]:
np.median(np_city[:, 0])

1.8449999999999998

In [9]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.        , 0.57973654],
       [0.57973654, 1.        ]])

In [10]:
np.std(np_city[:, 0])

0.2530261295246446

In [12]:
height = np.round(np.random.normal(1.75, 0.20, 5000),2)
weight = np.round(np.random.normal(60.32, 15, 5000),2)

np_city = np.column_stack((height, weight))

array([[ 1.88, 44.22],
       [ 1.89, 56.23],
       [ 1.9 , 76.45],
       ...,
       [ 1.79, 57.26],
       [ 1.13, 51.32],
       [ 1.91, 60.75]])