In [1]:
print("before")
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam)
print()

before
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]



In [2]:
print("after")
fam[7] = 1.86
print(fam)
print()

after
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]



In [3]:
fam[0:2] = ["lisa",1.74]
print(fam)

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]


In [4]:
# ADDING ELEMENTS
fam + ["me",1.79]

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]

In [6]:
# DELETE ELEMENTS 
fam_ext = fam + ["me", 1.79]
del(fam[2])
print(fam)

['lisa', 1.74, 'mom', 1.71, 'dad', 1.86]


In [10]:
# CHANGE ELEMENT 
name = ['albert', 'halawa', 'pratama']
print("before\n",name)
print() 
username = name
username[1] = "putra"
print("after\n",username)

before
 ['albert', 'halawa', 'pratama']

after
 ['albert', 'putra', 'pratama']


In [14]:
name = ['albert', 'halawa', 'pratama']
print("before\n",name)
print()
username = list(name)
username = name[:]
username[1] = "putra"
print("after\n",username)

before
 ['albert', 'halawa', 'pratama']

after
 ['albert', 'putra', 'pratama']


In [19]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
y

['a', 'b', 'c', 'd', 'e', 'f']

## List Recap

In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [2]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
weight/height ** 2

### FIXED

In [4]:
import numpy as np 
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [5]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [6]:
bmi = np_weight/np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## COMPARISON

In [ ]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight/height**2


In [8]:
np_height = np.array(height)
np_weight = np.array(weight)
np_weight/np_height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])