In [1]:
data = [1,2,3,4,2,1]
data.remove(2)
print(data)

[1, 3, 4, 2, 1]


In [5]:
import numpy as np

np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [6]:
np.array([1,2],[3,4])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [7]:
np.array([4,5,3,1 , 5,6,7])

array([4, 5, 3, 1, 5, 6, 7])

# No 3

In [8]:
y = [3,2,1]
y.reverse()
y

[1, 2, 3]

# No 4

In [ ]:
np.array([10, 15, 22, 13, 17, 20, 8])


xy = x[x <13]


In [9]:
import numpy as np
m = np.array([2, 6, 4])
n = np.array([2, 1, 1])
print(m * n)

[4 6 4]


# Intermmediate

In [10]:
diameter = { 
  'earth':1, 
  'jupiter': 11.21
}
print(diameter)


{'earth': 1, 'jupiter': 11.21}


In [14]:
import numpy as np
x = np.array([[9, 2, 2],
              [9, 8, 7]])
for i in np.nditer(x):
    print(i)

print()

for i in enumerate(x):
    print(i)

9
2
2
9
8
7

(0, array([9, 2, 2]))
(1, array([9, 8, 7]))


In [17]:
practice = {'python': 100, "r": 30, "sql": 10}
for key, value in practice.items():
  print(key + " practice has " + str(value) + " items")

python practice has 100 items
r practice has 30 items
sql practice has 10 items


In [21]:
print(False or True)

True
