In [5]:
import numpy 
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
from numpy import array
array([1,2,3])

### example

In [10]:
import numpy as np

fam = ['liz', 173, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

fam_ext = fam + ['me', 1.79]

print(str(len(fam_ext)) + ' element in fam_ext')

np_fam = np.array(fam_ext) #Clearly using numpy

10 element in fam_ext
